### ISSUE TITLE
Telegram plugin not found

### ISSUE THREAD

**Issue by ghost** [LEXASOFT/PHP-Censor-Telegram-Plugin#3]
Error when running build.
> RUNNING PLUGIN: telegram (Stage: Complete)
Plugin does not exist: telegram
PLUGIN: FAILED (ALLOWED)

Conf:
build_settings: 
  clone_depth: 1
  ignore: 
    - routes
    - config
    - database
    - bootstrap
    - resources
    - storage
    - vendor
    - public
    - tests
setup: 
  composer: 
    action: install
test: 
  php_cpd: 
    allow_failures: true
    ignore: 
      - routes
      - config
      - bootstrap
      - resources
      - database
      - storage
      - vendor
      - public
      - tests
  php_mess_detector: 
    allowed_warnings: -1
    ignore: 
      - routes
      - database
      - config
      - bootstrap
      - resources
      - storage
      - vendor
      - public
      - tests
complete:
    telegram:
        api_key: "redacted"
        message: "[%ICON_BUILD%] [%PROJECT_TITLE%](%PROJECT_URI%) - [Build #%BUILD%](%BUILD_URI%) has finished for commit [%SHORT_COMMIT% (%COMMIT_EMAIL%)](%COMMIT_URI%) on branch [%BRANCH%](%BRANCH_URI%)"
        recipients:
            - "redacted"
        send_log: true

**Comment by corpsee** [comment]
Can you give more details how did you install this plugin in PHP Censor?

**Comment by ghost** [comment]
I ran 
composer require lexasoft/php-censor-telegram-plugin
as opposed in the readme.md
And then added the config to my project config. Thrn did a test build and got the error "plugin telegram not found".

**Comment by corpsee** [comment]
Do you use worker or cron mode? If you use worker, did you restart worker?

**Comment by ghost** [comment]
I use a worker and I have rebooted the server. It now worked.
